//! Runner configuration file handling and auth-token/environment resolution.

use std::path::PathBuf;

use anyhow::{Context, Result};

/// Runner configuration file.
#[derive(Debug, Clone, serde::Deserialize, serde::Serialize, Default)]
pub(crate) struct RunnerConfig {
    pub(crate) server: Option<String>,
    pub(crate) token: Option<String>,
    pub(crate) runner_id: Option<i64>,
    pub(crate) name: Option<String>,
    pub(crate) labels: Option<Vec<String>>,
}

fn config_path(path: &str) -> PathBuf {
    let expanded = if let Some(remain) = path.strip_prefix('~') {
        match home::home_dir() {
            Some(home) => {
                let trimmed = remain.trim_start_matches('/');
                let mut result = home;
                if !trimmed.is_empty() {
                    result.push(trimmed);
                }
                result.to_string_lossy().to_string()
            }
            None => path.to_string(),
        }
    } else {
        path.to_string()
    };

    PathBuf::from(expanded)
}

/// Remediation appended to every runner config-file read failure. The file is
/// generated by `forgekeep-runner register --save`, so a broken one can always
/// be removed and regenerated.
const RUNNER_CONFIG_HINT: &str = "fix or delete it, then re-run \
     `forgekeep-runner register --save` to regenerate it (and bind-mount the file \
     itself, not a directory)";

/// Load the runner configuration file.
///
/// `Ok(None)` means the file genuinely **does not exist** — the legitimate
/// "no config yet" case that lets the runner fall back to CLI flags and
/// auto-registration. A file that exists but cannot be read (wrong permissions,
/// or a directory that a Docker bind-mount auto-created because the source file
/// was missing) or cannot be parsed (broken TOML) is an error and is reported
/// with the path and the cause.
///
/// Before this, both cases went through `.ok()?` and became a plain `None`, i.e.
/// "as if there were no config": the runner silently ignored an unreadable file
/// and re-registered under a fresh identity on every start, and "why does the
/// runner ignore my config" had to be debugged blind. Mirrors
/// `rg-cli/src/serve.rs::ensure_regular_file` + `load_config_file` for the
/// server-side config file (the crates share no dependency, hence the small
/// duplication).
pub(crate) fn load_config(path: &str) -> Result<Option<RunnerConfig>> {
    let p = config_path(path);
    let shown = p.display();

    let content = match std::fs::read_to_string(&p) {
        Ok(content) => content,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(error) => {
            if p.is_dir() {
                anyhow::bail!(
                    "runner config path `{shown}` is a directory, not a file — a Docker \
                     bind-mount likely auto-created it because the source file was missing; \
                     {RUNNER_CONFIG_HINT}"
                );
            }
            return Err(anyhow::Error::new(error)).with_context(|| {
                format!("failed to read runner config `{shown}` — {RUNNER_CONFIG_HINT}")
            });
        }
    };

    let config = toml::from_str(&content).with_context(|| {
        format!("failed to parse runner config `{shown}` as TOML — {RUNNER_CONFIG_HINT}")
    })?;
    tracing::debug!(path = %shown, "Loaded runner configuration file");
    Ok(Some(config))
}

pub(crate) fn save_config(path: &str, config: &RunnerConfig) -> Result<()> {
    let p = config_path(path);
    if let Some(parent) = p.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let content = toml::to_string_pretty(config)?;
    std::fs::write(&p, content)?;
    Ok(())
}

pub(crate) fn resolve_auth_token(auth_token: Option<String>) -> Option<String> {
    auth_token.or_else(|| env_var_compat("FORGEKEEP_AUTH_TOKEN", "IRONFORGE_AUTH_TOKEN"))
}

/// Read `new` from the environment, falling back to the deprecated `old` name
/// (IronForge → ForgeKeep rebrand) with a one-time deprecation warning.
fn env_var_compat(new: &str, old: &str) -> Option<String> {
    if let Ok(value) = std::env::var(new) {
        return Some(value);
    }
    match std::env::var(old) {
        Ok(value) => {
            tracing::warn!(
                "environment variable `{old}` is deprecated and will be removed in a future \
                 release; use `{new}` instead"
            );
            Some(value)
        }
        Err(_) => None,
    }
}

#[cfg(test)]
mod tests {
    use super::load_config;

    /// A missing config file is the legitimate "no config yet" case: the runner
    /// falls back to CLI flags and auto-registration, no diagnostics needed.
    #[test]
    fn a_missing_config_file_is_a_quiet_none() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("runner.toml");

        let loaded = load_config(path.to_str().unwrap()).expect("missing file must not be an error");

        assert!(loaded.is_none());
    }

    #[test]
    fn a_readable_config_file_is_parsed() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("runner.toml");
        std::fs::write(
            &path,
            r#"
server = "http://127.0.0.1:8080"
runner_id = 7
token = "tok"
name = "builder-1"
labels = ["linux", "docker"]
"#,
        )
        .unwrap();

        let cfg = load_config(path.to_str().unwrap())
            .expect("a valid config must load")
            .expect("a config file that exists must yield Some");

        assert_eq!(cfg.server.as_deref(), Some("http://127.0.0.1:8080"));
        assert_eq!(cfg.runner_id, Some(7));
        assert_eq!(cfg.token.as_deref(), Some("tok"));
        assert_eq!(cfg.name.as_deref(), Some("builder-1"));
        assert_eq!(
            cfg.labels.as_deref(),
            Some(["linux".to_string(), "docker".to_string()].as_slice())
        );
    }

    /// The bug: a broken TOML went through `.ok()?` and became `None`, so the
    /// runner behaved exactly as if the operator had never written the file.
    #[test]
    fn a_malformed_config_file_is_reported_with_path_and_cause() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("runner.toml");
        std::fs::write(&path, "server = \"http://127.0.0.1:8080\"\nthis is not toml\n").unwrap();

        let error = load_config(path.to_str().unwrap())
            .expect_err("a malformed config must not be silently treated as absent");

        let rendered = format!("{error:#}");
        assert!(
            rendered.contains(path.to_str().unwrap()),
            "error must name the config path: {rendered}"
        );
        assert!(
            rendered.contains("as TOML"),
            "error must say the file failed to parse: {rendered}"
        );
        assert!(
            rendered.contains("forgekeep-runner register --save"),
            "error must carry the remediation hint: {rendered}"
        );
    }

    /// The deploy incident that started this phase: a Docker bind-mount whose
    /// source file was missing leaves a *directory* at the config path.
    #[test]
    fn a_directory_at_the_config_path_is_reported_as_such() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("runner.toml");
        std::fs::create_dir(&path).unwrap();

        let error = load_config(path.to_str().unwrap())
            .expect_err("a directory at the config path must not be treated as absent");

        let rendered = format!("{error:#}");
        assert!(
            rendered.contains(path.to_str().unwrap()),
            "error must name the config path: {rendered}"
        );
        assert!(
            rendered.contains("is a directory"),
            "error must explain the directory case: {rendered}"
        );
    }

    /// An existing but unreadable file (mode 000) must be an error too, not a
    /// silent `None` — the "wrong uid inside the container" case.
    #[cfg(unix)]
    #[test]
    fn an_unreadable_config_file_is_reported_with_path() {
        use std::os::unix::fs::PermissionsExt;

        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("runner.toml");
        std::fs::write(&path, "server = \"http://127.0.0.1:8080\"\n").unwrap();
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o000)).unwrap();

        // root (and CI containers running as uid 0) bypass the permission bits
        // entirely, so there is nothing to observe there — probe instead of
        // guessing the uid.
        if std::fs::read_to_string(&path).is_ok() {
            return;
        }

        let error = load_config(path.to_str().unwrap())
            .expect_err("an unreadable config must not be silently treated as absent");

        let rendered = format!("{error:#}");
        assert!(
            rendered.contains(path.to_str().unwrap()),
            "error must name the config path: {rendered}"
        );
        assert!(
            rendered.contains("failed to read"),
            "error must say the read failed: {rendered}"
        );
    }
}
