//! Miscellaneous non-Git HTTP handlers: health check, SPA fallback, and the
//! OpenAPI / Swagger UI endpoints.

use axum::extract::{Extension, State};
use axum::http::{header, StatusCode};
use axum::response::{IntoResponse, Response};

use crate::{openapi, security, AppState};

/// H-2: SPA fallback handler — serves `index.html` with a per-request CSP
/// nonce injected into all `<script>` tags.
///
/// The nonce is generated by `security_headers_middleware` and stored in
/// request extensions. This handler reads it and injects `nonce="<value>"`
/// into every `<script>` tag so the browser allows inline scripts under
/// the strict `script-src 'self' 'nonce-<value>'` CSP.
pub(crate) async fn spa_index_handler(
    Extension(nonce): Extension<security::CspNonce>,
) -> Response {
    match tokio::fs::read("web/build/index.html").await {
        Ok(html_bytes) => {
            let html = String::from_utf8_lossy(&html_bytes).into_owned();
            let modified = security::inject_csp_nonce(&html, &nonce.0);
            (
                StatusCode::OK,
                [(header::CONTENT_TYPE, "text/html; charset=utf-8")],
                modified,
            )
                .into_response()
        }
        Err(_) => (StatusCode::NOT_FOUND, "index.html not found").into_response(),
    }
}

pub(crate) async fn health(State(state): State<AppState>) -> impl IntoResponse {
    use sea_orm::{ConnectionTrait, Statement};

    let mut checks = serde_json::Map::new();

    // DB ping
    let db_ok = state
        .db
        .execute(Statement::from_string(
            state.db.get_database_backend(),
            "SELECT 1".to_string(),
        ))
        .await
        .is_ok();
    checks.insert(
        "database".to_string(),
        serde_json::json!(if db_ok { "ok" } else { "error" }),
    );

    // Filesystem check
    let fs_ok = state.repo_root.exists() && state.repo_root.read_dir().is_ok();
    checks.insert(
        "filesystem".to_string(),
        serde_json::json!(if fs_ok { "ok" } else { "error" }),
    );

    // Prometheus registry check
    let metrics_ok = crate::metrics::REGISTRY.get().is_some();
    checks.insert(
        "metrics".to_string(),
        serde_json::json!(if metrics_ok { "ok" } else { "not_initialized" }),
    );

    // Git availability check (gateway already validates git --version at init)
    let git_ok = rg_git::cli_gateway::global_gateway().is_ok();
    checks.insert(
        "git".to_string(),
        serde_json::json!(if git_ok { "ok" } else { "error" }),
    );

    // SMTP connectivity check (TCP connect with timeout)
    let smtp_ok = if let Some(ref smtp) = state.smtp_config {
        match tokio::time::timeout(
            std::time::Duration::from_secs(3),
            tokio::net::TcpStream::connect((smtp.host.as_str(), smtp.port)),
        )
        .await
        {
            Ok(Ok(_)) => true,
            Ok(Err(_)) | Err(_) => false,
        }
    } else {
        true // skipped if not configured
    };
    checks.insert(
        "smtp".to_string(),
        serde_json::json!(if smtp_ok { "ok" } else { "error" }),
    );

    // Overall: all critical checks must pass
    let overall = if db_ok && fs_ok && git_ok && smtp_ok {
        "ok"
    } else if db_ok || fs_ok {
        "degraded"
    } else {
        "unhealthy"
    };
    let status_code = if db_ok && fs_ok && git_ok && smtp_ok {
        StatusCode::OK
    } else {
        StatusCode::SERVICE_UNAVAILABLE
    };

    (
        status_code,
        axum::Json(serde_json::json!({
            "status": overall,
            "version": env!("CARGO_PKG_VERSION"),
            "phase": 22,
            "checks": checks,
        })),
    )
}

/// GET /api-docs/openapi.json — serve the OpenAPI specification.
pub(crate) async fn openapi_handler() -> impl IntoResponse {
    (
        StatusCode::OK,
        [(header::CONTENT_TYPE, "application/json")],
        openapi::openapi_spec(),
    )
}

/// GET /api-docs/{*tail} — serve Swagger UI static files.
pub(crate) async fn swagger_ui_handler(
    axum::extract::Path(tail): axum::extract::Path<String>,
) -> Response {
    let path = if tail.is_empty() { "/" } else { &tail };
    swagger_ui_response(path)
}

/// GET /api-docs[/] — serve Swagger UI index.
pub(crate) async fn swagger_ui_root_handler() -> Response {
    swagger_ui_response("/")
}

fn swagger_ui_response(path: &str) -> Response {
    let config = openapi::swagger_config();

    match utoipa_swagger_ui::serve(path, config) {
        Ok(Some(file)) => (
            StatusCode::OK,
            [(header::CONTENT_TYPE, file.content_type)],
            file.bytes.to_vec(),
        ),
        Ok(None) => (
            StatusCode::NOT_FOUND,
            [(header::CONTENT_TYPE, "text/plain".to_string())],
            "Not Found".as_bytes().to_vec(),
        ),
        Err(e) => (
            StatusCode::INTERNAL_SERVER_ERROR,
            [(header::CONTENT_TYPE, "text/plain".to_string())],
            format!("Swagger UI error: {e}").into_bytes(),
        ),
    }
    .into_response()
}
