[package]
name = "rg-cli"
version = "0.1.0"
edition = "2021"
description = "ForgeKeep — self-hosted Git platform server (main binary)"
repository = "https://github.com/Yahook/ForgeKeep"
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "forgekeep"
path = "src/main.rs"

[dependencies]
rg-core = { path = "../rg-core" }
rg-git = { path = "../rg-git" }
rg-ssh = { path = "../rg-ssh" }
rg-http = { path = "../rg-http" }
rg-db = { path = "../rg-db" }
rg-ci = { path = "../rg-ci" }
gix = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true }
opentelemetry-otlp = { workspace = true }
tracing-opentelemetry = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
reqwest = { workspace = true }
rand = { workspace = true }
base64 = { workspace = true }

[lints]
workspace = true
