//! Turning a "who produced this row" foreign key from `ON DELETE CASCADE` into
//! `ON DELETE SET NULL`, on every backend.
//!
//! A column naming the account that *made* something is not a column naming the
//! account that *owns* it. The row lives wherever it was made — routinely
//! somebody else's repository or organization — so cascading from `users`
//! deletes other people's data when a collaborator's account goes away, and the
//! owner never finds out. The replacement is the rule every forge converged on:
//! the row stays and its author becomes a ghost.
//!
//! This module is the machinery, extracted from
//! `m20260805_000002_uploads_outlive_their_uploader` (the first migration to
//! apply the rule) so the ones that follow do not re-derive it — least of all
//! the SQLite half, where getting it wrong deletes data rather than failing.
//!
//! ## Per-backend notes
//!
//! **SQLite** — a foreign key's `ON DELETE` action is spelled inside
//! `CREATE TABLE`, so the whole table has to be rebuilt. The rebuild runs under
//! `PRAGMA foreign_keys = OFF` **and** `PRAGMA legacy_alter_table = ON`
//! together, on one pinned connection, inside one `BEGIN IMMEDIATE`, for the
//! reasons established by `m20260730_000001_repositories_namespace_unique`:
//! either pragma alone still lets SQLite rewrite a *child* table's `REFERENCES`
//! clause to follow the rename that starts the rebuild, after which the closing
//! `DROP TABLE` cascades every child row away. The combination is proven on the
//! live database — by renaming a throwaway parent and reading back whether its
//! child followed — before the first destructive statement runs.
//!
//! **Postgres / MySQL** — nullability and the foreign key are altered in place.
//! The old constraint's name was generated by the server, so it is looked up in
//! the catalogue by the column it sits on rather than assumed.
//!
//! ## `down`
//!
//! The reversal is real, not a half-revert: it restores `NOT NULL` and the
//! cascade. If any row has been ghosted since — the account is gone and there is
//! no id to put back — restoring `NOT NULL` fails loudly on every backend. That
//! is the honest answer; the author cannot be recovered, and silently deleting
//! other people's rows to make the constraint fit is the bug these migrations
//! exist to remove.

use std::future::Future;

use sea_orm::sqlx::{Executor as _, Row as _, Sqlite};
use sea_orm::{ConnectionTrait, DatabaseBackend, DatabaseConnection, Statement};
use sea_orm_migration::prelude::*;
use sea_orm_migration::SchemaManagerConnection;

/// Which rule the producing account's column is to carry.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum Shape {
    /// Nullable, `ON DELETE SET NULL` — the row outlives its author.
    Ghost,
    /// `NOT NULL`, `ON DELETE CASCADE` — the pre-migration rule.
    Owned,
}

impl Shape {
    fn nullability(self) -> &'static str {
        match self {
            Self::Ghost => "NULL",
            Self::Owned => "NOT NULL",
        }
    }

    fn on_delete(self) -> &'static str {
        match self {
            Self::Ghost => "SET NULL",
            Self::Owned => "CASCADE",
        }
    }
}

/// One table's SQLite rebuild recipe.
///
/// `columns` is checked against the live table before anything is dropped: a
/// rebuild that silently lost a column added by a migration it has not heard of
/// would be far worse than a refusal to run.
pub(crate) struct SqliteTable {
    pub name: &'static str,
    pub columns: &'static [&'static str],
    /// Column list of the replacement table, with `{rule}` standing in for the
    /// producing account's `NULL` / `NOT NULL`.
    pub body: &'static str,
    /// Foreign keys of the replacement table, with `{on_delete}` standing in for
    /// the producing account's `ON DELETE` action.
    pub foreign_keys: &'static str,
    /// Named indexes, dropped before the rebuild and recreated after it.
    /// Implicit `UNIQUE` indexes are part of `body` and need no handling.
    pub indexes: &'static [(&'static str, &'static str)],
    /// A statement pair that carries the table's `AUTOINCREMENT` high-water
    /// mark across the rebuild, with `{seq}` standing in for it. Inserted and
    /// deleted again inside the same transaction — see [`restore_sequence`].
    pub sequence_row: &'static str,
}

/// Where a test hook can interrupt a SQLite rebuild.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum SqliteRebuildPoint {
    WriteBoundary,
    TableRebuilt(&'static str),
    SchemaRestored,
}

/// One migration's worth of columns to move between the two shapes.
pub(crate) struct GhostAuthorRebuild {
    /// Migration name, quoted in every error this rebuild can raise.
    pub migration: &'static str,
    /// Suffix for the transient staging table each SQLite rebuild renames to.
    pub staging_suffix: &'static str,
    /// The `(table, column)` pairs, used by Postgres and MySQL directly and by
    /// the tests to read the applied shape back off the schema.
    pub columns: &'static [(&'static str, &'static str)],
    /// The same tables' SQLite rebuild recipes.
    pub sqlite_tables: &'static [SqliteTable],
    /// What is lost if the rebuild runs with foreign keys still enforced —
    /// spelled out in the refusal, because that is the sentence whoever hits it
    /// has to act on.
    pub cascade_warning: &'static str,
}

impl GhostAuthorRebuild {
    pub(crate) async fn apply(
        &self,
        manager: &SchemaManager<'_>,
        shape: Shape,
    ) -> Result<(), DbErr> {
        match manager.get_database_backend() {
            DatabaseBackend::Sqlite => self.sqlite(manager, shape).await,
            DatabaseBackend::Postgres => self.postgres(manager, shape).await,
            DatabaseBackend::MySql => self.mysql(manager, shape).await,
        }
    }

    // ── SQLite ──────────────────────────────────────────────────────────────

    /// Rebuild every table with the requested rule, on one pinned connection
    /// under an explicit write boundary.
    ///
    /// `foreign_keys` and `legacy_alter_table` are connection-local and cannot
    /// be changed after a transaction starts. Acquiring the connection first
    /// lets us establish and verify those settings, then `BEGIN IMMEDIATE`
    /// excludes every other writer for the whole rebuild. SQLite DDL is
    /// transactional, so any error restores every table, index and sequence
    /// together.
    pub(crate) async fn sqlite(
        &self,
        manager: &SchemaManager<'_>,
        shape: Shape,
    ) -> Result<(), DbErr> {
        self.sqlite_with_hook(manager, shape, |_| async { Ok(()) })
            .await
    }

    /// The rebuild, with a hook the tests use to fail it at a chosen point.
    pub(crate) async fn sqlite_with_hook<F, Fut>(
        &self,
        manager: &SchemaManager<'_>,
        shape: Shape,
        after_step: F,
    ) -> Result<(), DbErr>
    where
        F: Fn(SqliteRebuildPoint) -> Fut,
        Fut: Future<Output = Result<(), DbErr>>,
    {
        let migration = self.migration;
        let pool = match manager.get_connection() {
            SchemaManagerConnection::Connection(
                db @ DatabaseConnection::SqlxSqlitePoolConnection(_),
            ) => db.get_sqlite_connection_pool(),
            SchemaManagerConnection::Connection(_) => {
                return Err(DbErr::Migration(format!(
                    "{migration}: SQLite rebuild received a non-SQLite connection"
                )));
            }
            SchemaManagerConnection::Transaction(_) => {
                return Err(DbErr::Migration(format!(
                    "{migration}: SQLite rebuild requires a non-transactional migration \
                     connection so its connection-local PRAGMAs can be set before BEGIN"
                )));
            }
        };
        let mut connection = pool
            .acquire()
            .await
            .map_err(|error| self.error("acquire a dedicated connection", error))?;

        let mut sequences = Vec::with_capacity(self.sqlite_tables.len());
        for table in self.sqlite_tables {
            self.assert_sqlite_columns(&mut connection, table).await?;
            sequences.push(self.autoincrement_seq(&mut connection, table.name).await?);
        }

        if let Err(error) = self.prepare_connection(&mut connection).await {
            return self.finish(&mut connection, Err(error), false).await;
        }

        if let Err(error) = self
            .execute(
                &mut connection,
                "begin the write boundary",
                "BEGIN IMMEDIATE",
            )
            .await
        {
            return self.finish(&mut connection, Err(error), false).await;
        }

        let work_result = async {
            after_step(SqliteRebuildPoint::WriteBoundary).await?;
            for (table, sequence) in self.sqlite_tables.iter().zip(sequences) {
                self.rebuild_one_table(&mut connection, table, shape, sequence)
                    .await?;
                after_step(SqliteRebuildPoint::TableRebuilt(table.name)).await?;
            }
            self.assert_referential_integrity(&mut connection).await?;
            after_step(SqliteRebuildPoint::SchemaRestored).await?;
            self.execute(&mut connection, "commit the rebuilt tables", "COMMIT")
                .await
        }
        .await;

        self.finish(&mut connection, work_result, true).await
    }

    async fn rebuild_one_table(
        &self,
        connection: &mut SqlitePoolConnection,
        table: &SqliteTable,
        shape: Shape,
        sequence: Option<i64>,
    ) -> Result<(), DbErr> {
        let name = table.name;
        let staging = format!("{name}{}", self.staging_suffix);
        let columns = table
            .columns
            .iter()
            .map(|column| format!("\"{column}\""))
            .collect::<Vec<_>>()
            .join(", ");
        let body = table.body.replace("{rule}", shape.nullability());
        let foreign_keys = table.foreign_keys.replace("{on_delete}", shape.on_delete());

        let drop_indexes = table
            .indexes
            .iter()
            .map(|(index, _)| format!("DROP INDEX IF EXISTS \"{index}\";"))
            .collect::<String>();
        self.execute(
            connection,
            &format!("drop the {name} indexes"),
            &drop_indexes,
        )
        .await?;

        self.execute(
            connection,
            &format!("copy {name} into the replacement table"),
            &format!(
                r#"
            ALTER TABLE "{name}" RENAME TO "{staging}";

            CREATE TABLE "{name}" ({body},{foreign_keys}
            );

            INSERT INTO "{name}" ({columns}) SELECT {columns} FROM "{staging}";

            DROP TABLE "{staging}";
            "#
            ),
        )
        .await?;

        let restore_indexes = table
            .indexes
            .iter()
            .map(|(_, statement)| *statement)
            .collect::<Vec<_>>()
            .join("\n");
        self.execute(
            connection,
            &format!("restore the {name} indexes"),
            &restore_indexes,
        )
        .await?;

        self.restore_sequence(connection, table, sequence).await
    }

    /// Put the table's `AUTOINCREMENT` high-water mark back.
    ///
    /// The replacement table's counter starts from the highest id copied in,
    /// which is lower than the old one whenever the most recent row was
    /// hard-deleted — and these ids are handed out to the world (a release
    /// asset's id is part of its blob key; a status or key id is what an API
    /// caller stored), so a reused id names something a previous row may still
    /// own. A direct `sqlite_sequence` UPDATE inside this transaction is
    /// overwritten by SQLite's in-memory sequence state at commit, so the mark
    /// is advanced through a real, temporary row instead.
    async fn restore_sequence(
        &self,
        connection: &mut SqlitePoolConnection,
        table: &SqliteTable,
        sequence: Option<i64>,
    ) -> Result<(), DbErr> {
        let Some(sequence) = sequence else {
            return Ok(());
        };
        self.execute(
            connection,
            &format!("restore the {} AUTOINCREMENT high-water mark", table.name),
            &table.sequence_row.replace("{seq}", &sequence.to_string()),
        )
        .await
    }

    /// Prove, on this database, that the two pragmas the rebuild depends on
    /// still do what it needs — before it touches a row.
    ///
    /// A child table carrying `REFERENCES "<parent>"` must keep pointing at the
    /// *name* when the parent is renamed out of the way: the replacement table
    /// then inherits the reference and dropping the old one cascades nothing.
    /// Otherwise SQLite rewrites the clause to follow the rename and the
    /// `DROP TABLE` that ends the rebuild silently takes every child row with
    /// it.
    ///
    /// Getting that property needs **both** pragmas, which is not what either
    /// one's documentation suggests on its own (established by experiment in
    /// `m20260730_000001_repositories_namespace_unique`): `foreign_keys = ON`
    /// rewrites the clauses whatever `legacy_alter_table` says, and
    /// `legacy_alter_table = OFF` rewrites them whatever `foreign_keys` says.
    /// `foreign_keys = OFF` is separately what stops `DROP TABLE`'s implicit
    /// `DELETE` from firing `ON DELETE CASCADE`.
    ///
    /// Both are also per-connection and no-ops inside a transaction, and SeaORM
    /// happens not to wrap SQLite migrations in one — an implementation detail
    /// of a dependency, holding up the difference between a migration and a data
    /// loss. So rather than trust the combination, exercise it.
    async fn prepare_connection(&self, connection: &mut SqlitePoolConnection) -> Result<(), DbErr> {
        self.execute(
            connection,
            "disable foreign keys on the rebuild connection",
            "PRAGMA foreign_keys = OFF",
        )
        .await?;
        self.execute(
            connection,
            "enable legacy ALTER TABLE semantics on the rebuild connection",
            "PRAGMA legacy_alter_table = ON",
        )
        .await?;

        let foreign_keys = self
            .scalar(
                connection,
                "read PRAGMA foreign_keys",
                "PRAGMA foreign_keys",
            )
            .await?
            .unwrap_or(-1);
        let legacy_alter_table = self
            .scalar(
                connection,
                "read PRAGMA legacy_alter_table",
                "PRAGMA legacy_alter_table",
            )
            .await?
            .unwrap_or(-1);
        if foreign_keys != 0 || legacy_alter_table != 1 {
            return Err(DbErr::Migration(format!(
                "{}: refusing to rebuild — the dedicated connection reported \
                 foreign_keys={foreign_keys} and legacy_alter_table={legacy_alter_table}, \
                 expected 0 and 1",
                self.migration
            )));
        }

        self.assert_foreign_keys_can_be_suspended(connection).await
    }

    async fn assert_foreign_keys_can_be_suspended(
        &self,
        connection: &mut SqlitePoolConnection,
    ) -> Result<(), DbErr> {
        const PARENT: &str = "_forgekeep_ghost_probe_parent";
        const CHILD: &str = "_forgekeep_ghost_probe_child";
        const RENAMED: &str = "_forgekeep_ghost_probe_parent_renamed";

        let probe_result = async {
            self.execute(
                connection,
                "exercise the foreign-key rename probe",
                &format!(
                    r#"
                DROP TABLE IF EXISTS "{CHILD}";
                DROP TABLE IF EXISTS "{PARENT}";
                DROP TABLE IF EXISTS "{RENAMED}";
                CREATE TABLE "{PARENT}" ("id" integer NOT NULL PRIMARY KEY);
                CREATE TABLE "{CHILD}" (
                    "id" integer NOT NULL PRIMARY KEY,
                    "pid" integer NULL REFERENCES "{PARENT}" ("id") ON DELETE CASCADE
                );
                ALTER TABLE "{PARENT}" RENAME TO "{RENAMED}";
                "#
                ),
            )
            .await?;

            self.optional_string(
                connection,
                "read the foreign-key rename probe",
                &format!("SELECT sql FROM sqlite_master WHERE type = 'table' AND name = '{CHILD}'"),
            )
            .await
        }
        .await;

        let cleanup_result = self
            .execute(
                connection,
                "remove the foreign-key rename probe",
                &format!(r#"DROP TABLE IF EXISTS "{CHILD}"; DROP TABLE IF EXISTS "{RENAMED}";"#),
            )
            .await;

        let child_sql = match (probe_result, cleanup_result) {
            (Ok(child_sql), Ok(())) => child_sql,
            (Err(error), Ok(())) => return Err(error),
            (Ok(_), Err(cleanup_error)) => return Err(cleanup_error),
            (Err(error), Err(cleanup_error)) => {
                return Err(combine_errors(error, vec![cleanup_error]));
            }
        };

        let followed_the_rename = child_sql.as_deref().is_none_or(|sql| sql.contains(RENAMED));

        if followed_the_rename {
            return Err(DbErr::Migration(format!(
                "{}: refusing to rebuild — on this connection `PRAGMA foreign_keys = OFF` did \
                 not take effect (the probe table's REFERENCES clause followed the rename: \
                 {child_sql:?}). {}",
                self.migration, self.cascade_warning
            )));
        }

        Ok(())
    }

    /// Fail loudly if the rebuild left a dangling reference behind.
    async fn assert_referential_integrity(
        &self,
        connection: &mut SqlitePoolConnection,
    ) -> Result<(), DbErr> {
        let violations = self
            .scalar(
                connection,
                "check the rebuilt tables' foreign keys",
                "SELECT count(*) FROM pragma_foreign_key_check",
            )
            .await?
            .unwrap_or(0);

        if violations > 0 {
            return Err(DbErr::Migration(format!(
                "{}: the rebuild left {violations} dangling foreign key reference(s) behind",
                self.migration
            )));
        }

        Ok(())
    }

    /// Refuse to rebuild a table whose columns are not the ones this migration
    /// knows how to copy.
    async fn assert_sqlite_columns(
        &self,
        connection: &mut SqlitePoolConnection,
        table: &SqliteTable,
    ) -> Result<(), DbErr> {
        let name = table.name;
        let rows = (&mut **connection)
            .fetch_all(format!("SELECT name FROM pragma_table_info('{name}')").as_str())
            .await
            .map_err(|error| self.error(&format!("read the {name} columns"), error))?;

        let mut live = rows
            .iter()
            .map(|row| {
                row.try_get::<String, _>(0)
                    .map_err(|error| self.error(&format!("decode a {name} column"), error))
            })
            .collect::<Result<Vec<_>, _>>()?;
        live.sort();

        let mut expected: Vec<String> = table.columns.iter().map(|c| (*c).to_string()).collect();
        expected.sort();

        if live != expected {
            return Err(DbErr::Migration(format!(
                "{}: refusing to rebuild `{name}` — its columns are {live:?}, but this migration \
                 copies {expected:?}. A column was added to the table without updating the \
                 migration's rebuild recipe; rebuilding now would drop it.",
                self.migration
            )));
        }

        Ok(())
    }

    /// The current `AUTOINCREMENT` high-water mark for a table, if any.
    async fn autoincrement_seq(
        &self,
        connection: &mut SqlitePoolConnection,
        table: &str,
    ) -> Result<Option<i64>, DbErr> {
        self.scalar(
            connection,
            &format!("read the {table} AUTOINCREMENT high-water mark"),
            &format!("SELECT seq FROM sqlite_sequence WHERE name = '{table}'"),
        )
        .await
    }

    async fn execute(
        &self,
        connection: &mut SqlitePoolConnection,
        action: &str,
        sql: &str,
    ) -> Result<(), DbErr> {
        (&mut **connection)
            .execute(sql)
            .await
            .map(|_| ())
            .map_err(|error| self.error(action, error))
    }

    async fn scalar(
        &self,
        connection: &mut SqlitePoolConnection,
        action: &str,
        sql: &str,
    ) -> Result<Option<i64>, DbErr> {
        (&mut **connection)
            .fetch_optional(sql)
            .await
            .map_err(|error| self.error(action, error))?
            .map(|row| {
                row.try_get::<i64, _>(0)
                    .map_err(|error| self.error(action, error))
            })
            .transpose()
    }

    async fn optional_string(
        &self,
        connection: &mut SqlitePoolConnection,
        action: &str,
        sql: &str,
    ) -> Result<Option<String>, DbErr> {
        (&mut **connection)
            .fetch_optional(sql)
            .await
            .map_err(|error| self.error(action, error))?
            .map(|row| {
                row.try_get::<String, _>(0)
                    .map_err(|error| self.error(action, error))
            })
            .transpose()
    }

    async fn finish(
        &self,
        connection: &mut SqlitePoolConnection,
        work_result: Result<(), DbErr>,
        transaction_started: bool,
    ) -> Result<(), DbErr> {
        let mut cleanup_errors = Vec::new();
        if work_result.is_err() && transaction_started {
            if let Err(error) = self
                .execute(connection, "roll back the rebuilt tables", "ROLLBACK")
                .await
            {
                cleanup_errors.push(error);
            }
        }
        if let Err(error) = self
            .execute(
                connection,
                "disable legacy ALTER TABLE semantics",
                "PRAGMA legacy_alter_table = OFF",
            )
            .await
        {
            cleanup_errors.push(error);
        }
        if let Err(error) = self
            .execute(
                connection,
                "restore foreign-key enforcement",
                "PRAGMA foreign_keys = ON",
            )
            .await
        {
            cleanup_errors.push(error);
        }

        match (work_result, cleanup_errors.is_empty()) {
            (Ok(()), true) => Ok(()),
            (Ok(()), false) => {
                connection.close_on_drop();
                Err(combine_errors(
                    DbErr::Migration(format!(
                        "{}: SQLite rebuild committed but connection cleanup failed",
                        self.migration
                    )),
                    cleanup_errors,
                ))
            }
            (Err(error), true) => Err(error),
            (Err(error), false) => {
                connection.close_on_drop();
                Err(combine_errors(error, cleanup_errors))
            }
        }
    }

    fn error(&self, action: &str, error: sea_orm::sqlx::Error) -> DbErr {
        DbErr::Migration(format!(
            "{}: SQLite rebuild failed to {action}: {error}",
            self.migration
        ))
    }

    // ── Postgres ────────────────────────────────────────────────────────────

    async fn postgres(&self, manager: &SchemaManager<'_>, shape: Shape) -> Result<(), DbErr> {
        let db = manager.get_connection();

        for (table, column) in self.columns {
            // Named rather than server-generated, so the reversal can find it by
            // the same route this call created it.
            let constraint = format!("fk_{table}_{column}_users");
            if let Some(existing) = self.postgres_foreign_key(manager, table, column).await? {
                db.execute_unprepared(&format!(
                    r#"ALTER TABLE "{table}" DROP CONSTRAINT "{existing}""#
                ))
                .await?;
            }

            let nullability = match shape {
                Shape::Ghost => "DROP NOT NULL",
                Shape::Owned => "SET NOT NULL",
            };
            db.execute_unprepared(&format!(
                r#"ALTER TABLE "{table}" ALTER COLUMN "{column}" {nullability}"#
            ))
            .await?;

            db.execute_unprepared(&format!(
                r#"ALTER TABLE "{table}" ADD CONSTRAINT "{constraint}"
                   FOREIGN KEY ("{column}") REFERENCES "users" ("id") ON DELETE {}"#,
                shape.on_delete()
            ))
            .await?;
        }

        Ok(())
    }

    /// Name of the foreign key on `table.column` that points at `users`.
    ///
    /// Looked up rather than assumed: the constraint was declared inline by
    /// SeaORM and its name is whatever the server generated.
    async fn postgres_foreign_key(
        &self,
        manager: &SchemaManager<'_>,
        table: &str,
        column: &str,
    ) -> Result<Option<String>, DbErr> {
        let row = manager
            .get_connection()
            .query_one(Statement::from_sql_and_values(
                DatabaseBackend::Postgres,
                r#"
            SELECT con.conname AS conname
            FROM pg_constraint con
            JOIN pg_class rel ON rel.oid = con.conrelid
            JOIN pg_namespace ns ON ns.oid = rel.relnamespace
            JOIN pg_class ref ON ref.oid = con.confrelid
            WHERE rel.relname = $1
              AND ns.nspname = current_schema()
              AND con.contype = 'f'
              AND ref.relname = 'users'
              AND (
                SELECT string_agg(att.attname::text, ',' ORDER BY att.attname)
                FROM unnest(con.conkey) AS k(attnum)
                JOIN pg_attribute att
                  ON att.attrelid = con.conrelid AND att.attnum = k.attnum
              ) = $2
            LIMIT 1
            "#,
                [table.into(), column.into()],
            ))
            .await?;

        match row {
            Some(row) => Ok(Some(row.try_get::<String>("", "conname")?)),
            None => Ok(None),
        }
    }

    // ── MySQL ───────────────────────────────────────────────────────────────

    async fn mysql(&self, manager: &SchemaManager<'_>, shape: Shape) -> Result<(), DbErr> {
        let db = manager.get_connection();

        for (table, column) in self.columns {
            let constraint = format!("fk_{table}_{column}_users");
            if let Some(existing) = self.mysql_foreign_key(manager, table, column).await? {
                db.execute_unprepared(&format!(
                    "ALTER TABLE `{table}` DROP FOREIGN KEY `{existing}`"
                ))
                .await?;
            }

            // MySQL has no "alter only the nullability": the column has to be
            // restated, and `bigint` is what every column these migrations move
            // is declared as.
            db.execute_unprepared(&format!(
                "ALTER TABLE `{table}` MODIFY `{column}` BIGINT {}",
                shape.nullability()
            ))
            .await?;

            // Dropping the foreign key leaves its index behind, which is what
            // the re-added constraint needs to live on — so no index is created
            // here.
            db.execute_unprepared(&format!(
                "ALTER TABLE `{table}` ADD CONSTRAINT `{constraint}`
                 FOREIGN KEY (`{column}`) REFERENCES `users` (`id`) ON DELETE {}",
                shape.on_delete()
            ))
            .await?;
        }

        Ok(())
    }

    /// Name of the foreign key on `table.column` that points at `users`.
    async fn mysql_foreign_key(
        &self,
        manager: &SchemaManager<'_>,
        table: &str,
        column: &str,
    ) -> Result<Option<String>, DbErr> {
        let row = manager
            .get_connection()
            .query_one(Statement::from_sql_and_values(
                DatabaseBackend::MySql,
                "SELECT k.CONSTRAINT_NAME AS name
             FROM information_schema.KEY_COLUMN_USAGE k
             WHERE k.TABLE_SCHEMA = DATABASE()
               AND k.TABLE_NAME = ?
               AND k.COLUMN_NAME = ?
               AND k.REFERENCED_TABLE_NAME = 'users'
             LIMIT 1",
                [table.into(), column.into()],
            ))
            .await?;

        match row {
            Some(row) => Ok(Some(row.try_get::<String>("", "name")?)),
            None => Ok(None),
        }
    }
}

type SqlitePoolConnection = sea_orm::sqlx::pool::PoolConnection<Sqlite>;

fn combine_errors(primary: DbErr, cleanup: Vec<DbErr>) -> DbErr {
    let cleanup = cleanup
        .into_iter()
        .map(|error| error.to_string())
        .collect::<Vec<_>>()
        .join("; ");
    DbErr::Migration(format!("{primary}; cleanup also failed: {cleanup}"))
}
