//! An account's departure must not delete other people's files.
//!
//! Three columns named the account that *produced* a piece of content, and all
//! three were declared `REFERENCES users(id) ON DELETE CASCADE`:
//!
//! * `attachments.uploader_id` (`m20260714_000001_create_attachments`)
//! * `release_assets.uploader_id` (`m20260508_000002_create_releases`)
//! * `releases.author_id` (`m20260508_000002_create_releases`)
//!
//! None of those rows belong to the uploader — they live in whichever
//! repository the file was uploaded *into*, which is routinely somebody else's.
//! So `DELETE FROM users` destroyed attachments inside other people's issues,
//! assets inside other people's releases and, through
//! `release_assets.release_id ON DELETE CASCADE`, entire releases of other
//! people's repositories together with every asset any account had ever
//! uploaded to them.
//!
//! The bytes did not go with them. `attachments/<repo_id>/<uuid>/<file>` and
//! `releases/<owner>/<repo>/<release_id>/<asset_id>/<file>` stay live: the
//! repository is not being deleted, so no retirement path walks its prefixes,
//! and the row that named the object is gone, so nothing can ever find it
//! again. In the UI the release simply loses its files (card_1cfc81035e92).
//!
//! The replacement is the answer every forge converged on: the *content* stays
//! and its author becomes a ghost. Each column becomes nullable with
//! `ON DELETE SET NULL`, so the database itself — not one careful call site —
//! guarantees that removing an account cannot remove a file from a repository
//! that is still alive. `pr_events.actor_id` already carried exactly this rule
//! (`m20260712_000001_create_pr_events`); this migration extends it to the three
//! columns that own bytes.
//!
//! What still cascades is unchanged and correct: the *repository* the content
//! lives in (`repo_id` / `release_id`), whose own deletion retires the storage
//! first through the staged, compensated path.
//!
//! ## Per-backend notes
//!
//! **SQLite** — a foreign key's `ON DELETE` action is spelled inside
//! `CREATE TABLE`, so each of the three tables has to be rebuilt. The rebuild
//! runs under `PRAGMA foreign_keys = OFF` **and**
//! `PRAGMA legacy_alter_table = ON` together, on one pinned connection, inside
//! one `BEGIN IMMEDIATE`, for the reasons established by
//! `m20260730_000001_repositories_namespace_unique`: either pragma alone still
//! lets SQLite rewrite the `REFERENCES "releases"` clause in `release_assets`
//! to follow the rename, after which the closing `DROP TABLE` would cascade
//! every asset away. The combination is proven on this database — by renaming a
//! throwaway parent and reading back whether its child followed — before the
//! first destructive statement runs.
//!
//! **Postgres / MySQL** — nullability and the foreign key are altered in place.
//! The constraint's name was generated by the server, so it is looked up in the
//! catalogue by the column it sits on rather than assumed.
//!
//! ## `down`
//!
//! The reversal is real, not a half-revert: it restores `NOT NULL` and the
//! cascade. If any row has been ghosted since — the account that uploaded it is
//! gone and there is no id to put back — restoring `NOT NULL` fails loudly on
//! every backend. That is the honest answer; the uploader cannot be recovered,
//! and silently deleting other people's files to make the constraint fit is the
//! bug this migration exists to remove.

use std::future::Future;

use sea_orm::sqlx::{Executor as _, Row as _, Sqlite};
use sea_orm::{ConnectionTrait, DatabaseBackend, DatabaseConnection, Statement};
use sea_orm_migration::prelude::*;
use sea_orm_migration::SchemaManagerConnection;

pub struct Migration;

impl MigrationName for Migration {
    fn name(&self) -> &str {
        "m20260805_000002_uploads_outlive_their_uploader"
    }
}

/// The three (table, column) pairs whose `ON DELETE` action this migration
/// turns from `CASCADE` into `SET NULL`.
const GHOSTED_COLUMNS: [(&str, &str); 3] = [
    ("releases", "author_id"),
    ("release_assets", "uploader_id"),
    ("attachments", "uploader_id"),
];

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        match manager.get_database_backend() {
            DatabaseBackend::Sqlite => sqlite_rebuild(manager, Shape::Ghost).await,
            DatabaseBackend::Postgres => postgres_apply(manager, Shape::Ghost).await,
            DatabaseBackend::MySql => mysql_apply(manager, Shape::Ghost).await,
        }
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        match manager.get_database_backend() {
            DatabaseBackend::Sqlite => sqlite_rebuild(manager, Shape::Owned).await,
            DatabaseBackend::Postgres => postgres_apply(manager, Shape::Owned).await,
            DatabaseBackend::MySql => mysql_apply(manager, Shape::Owned).await,
        }
    }
}

/// Which rule the producing account's column is to carry.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum Shape {
    /// Nullable, `ON DELETE SET NULL` — the content outlives its author.
    Ghost,
    /// `NOT NULL`, `ON DELETE CASCADE` — the pre-migration rule.
    Owned,
}

impl Shape {
    fn nullability(self) -> &'static str {
        match self {
            Self::Ghost => "NULL",
            Self::Owned => "NOT NULL",
        }
    }

    fn on_delete(self) -> &'static str {
        match self {
            Self::Ghost => "SET NULL",
            Self::Owned => "CASCADE",
        }
    }
}

// ── SQLite ──────────────────────────────────────────────────────────────────

/// One table's rebuild recipe.
///
/// `columns` is checked against the live table before anything is dropped: a
/// rebuild that silently lost a column added by a migration this one has not
/// heard of would be far worse than a refusal to run.
struct SqliteTable {
    name: &'static str,
    columns: &'static [&'static str],
    /// Column list of the replacement table, with `{rule}` standing in for the
    /// producing account's `NULL` / `NOT NULL`.
    body: &'static str,
    /// Foreign keys of the replacement table, with `{on_delete}` standing in
    /// for the producing account's `ON DELETE` action.
    foreign_keys: &'static str,
    /// Named indexes, dropped before the rebuild and recreated after it.
    /// Implicit `UNIQUE` indexes are part of `body` and need no handling.
    indexes: &'static [(&'static str, &'static str)],
    /// A row that carries the table's `AUTOINCREMENT` high-water mark, with
    /// `{seq}` standing in for it. Inserted and deleted again inside the same
    /// transaction — see `restore_sequence`.
    sequence_row: &'static str,
}

const SQLITE_TABLES: [SqliteTable; 3] = [
    SqliteTable {
        name: "releases",
        columns: &[
            "id",
            "repo_id",
            "tag_name",
            "target_commitish",
            "title",
            "body",
            "is_draft",
            "is_prerelease",
            "author_id",
            "created_at",
            "updated_at",
        ],
        body: r#"
            "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
            "repo_id" bigint NOT NULL,
            "tag_name" varchar NOT NULL,
            "target_commitish" varchar NOT NULL DEFAULT 'main',
            "title" varchar NOT NULL,
            "body" text NULL,
            "is_draft" boolean NOT NULL DEFAULT FALSE,
            "is_prerelease" boolean NOT NULL DEFAULT FALSE,
            "author_id" bigint {rule},
            "created_at" timestamp_with_timezone_text NOT NULL,
            "updated_at" timestamp_with_timezone_text NOT NULL,
            CONSTRAINT "idx_releases_repo_tag_unique" UNIQUE ("repo_id", "tag_name")"#,
        foreign_keys: r#"
            FOREIGN KEY ("repo_id") REFERENCES "repositories" ("id") ON DELETE CASCADE,
            FOREIGN KEY ("author_id") REFERENCES "users" ("id") ON DELETE {on_delete}"#,
        indexes: &[(
            "idx_releases_repo_id",
            r#"CREATE INDEX "idx_releases_repo_id" ON "releases" ("repo_id");"#,
        )],
        sequence_row: r#"
            INSERT INTO releases
                (id, repo_id, tag_name, target_commitish, title, created_at, updated_at)
            SELECT {seq}, 0, '_forgekeep_sequence_high_water', 'main', 'x',
                   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
            WHERE {seq} > COALESCE((SELECT MAX(id) FROM releases), 0);
            DELETE FROM releases
            WHERE id = {seq} AND repo_id = 0 AND tag_name = '_forgekeep_sequence_high_water';"#,
    },
    SqliteTable {
        name: "release_assets",
        columns: &[
            "id",
            "release_id",
            "filename",
            "size",
            "content_type",
            "download_count",
            "uploader_id",
            "created_at",
            "sha256",
            "attestation",
        ],
        body: r#"
            "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
            "release_id" bigint NOT NULL,
            "filename" varchar NOT NULL,
            "size" bigint NOT NULL DEFAULT 0,
            "content_type" varchar NOT NULL DEFAULT 'application/octet-stream',
            "download_count" bigint NOT NULL DEFAULT 0,
            "uploader_id" bigint {rule},
            "created_at" timestamp_with_timezone_text NOT NULL,
            "sha256" varchar NULL,
            "attestation" text NULL"#,
        foreign_keys: r#"
            FOREIGN KEY ("release_id") REFERENCES "releases" ("id") ON DELETE CASCADE,
            FOREIGN KEY ("uploader_id") REFERENCES "users" ("id") ON DELETE {on_delete}"#,
        indexes: &[(
            "idx_release_assets_release_id",
            r#"CREATE INDEX "idx_release_assets_release_id" ON "release_assets" ("release_id");"#,
        )],
        // `uploader_id` is NOT NULL in the `Owned` shape, so the probe row has
        // to carry one; user 0 does not exist, which is why the rebuild's
        // foreign keys are off while it lands and gone again before they are
        // back on.
        sequence_row: r#"
            INSERT INTO release_assets
                (id, release_id, filename, size, content_type, download_count, uploader_id,
                 created_at)
            SELECT {seq}, 0, '_forgekeep_sequence_high_water', 0, 'application/octet-stream', 0, 0,
                   CURRENT_TIMESTAMP
            WHERE {seq} > COALESCE((SELECT MAX(id) FROM release_assets), 0);
            DELETE FROM release_assets
            WHERE id = {seq} AND release_id = 0
              AND filename = '_forgekeep_sequence_high_water';"#,
    },
    SqliteTable {
        name: "attachments",
        columns: &[
            "id",
            "uuid",
            "repo_id",
            "uploader_id",
            "issue_id",
            "pull_request_id",
            "issue_comment_id",
            "review_comment_id",
            "filename",
            "blob_key",
            "content_type",
            "size",
            "download_count",
            "created_at",
            "sha256",
        ],
        body: r#"
            "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
            "uuid" varchar(36) NOT NULL UNIQUE,
            "repo_id" bigint NOT NULL,
            "uploader_id" bigint {rule},
            "issue_id" bigint NULL,
            "pull_request_id" bigint NULL,
            "issue_comment_id" bigint NULL,
            "review_comment_id" bigint NULL,
            "filename" varchar(255) NOT NULL,
            "blob_key" varchar(1024) NOT NULL,
            "content_type" varchar(255) NOT NULL,
            "size" bigint NOT NULL,
            "download_count" bigint NOT NULL DEFAULT 0,
            "created_at" timestamp_with_timezone_text NOT NULL,
            "sha256" varchar NULL"#,
        foreign_keys: r#"
            FOREIGN KEY ("repo_id") REFERENCES "repositories" ("id") ON DELETE CASCADE,
            FOREIGN KEY ("uploader_id") REFERENCES "users" ("id") ON DELETE {on_delete},
            FOREIGN KEY ("issue_id") REFERENCES "issues" ("id") ON DELETE CASCADE,
            FOREIGN KEY ("pull_request_id") REFERENCES "pull_requests" ("id") ON DELETE CASCADE,
            FOREIGN KEY ("issue_comment_id") REFERENCES "issue_comments" ("id") ON DELETE CASCADE,
            FOREIGN KEY ("review_comment_id") REFERENCES "review_comments" ("id") ON DELETE CASCADE"#,
        indexes: &[
            (
                "idx_attachments_blob_key",
                r#"CREATE UNIQUE INDEX "idx_attachments_blob_key" ON "attachments" ("blob_key");"#,
            ),
            (
                "idx_attachments_repo",
                r#"CREATE INDEX "idx_attachments_repo" ON "attachments" ("repo_id");"#,
            ),
            (
                "idx_attachments_issue",
                r#"CREATE INDEX "idx_attachments_issue" ON "attachments" ("issue_id");"#,
            ),
            (
                "idx_attachments_pr",
                r#"CREATE INDEX "idx_attachments_pr" ON "attachments" ("pull_request_id");"#,
            ),
            (
                "idx_attachments_issue_comment",
                r#"CREATE INDEX "idx_attachments_issue_comment" ON "attachments" ("issue_comment_id");"#,
            ),
            (
                "idx_attachments_review_comment",
                r#"CREATE INDEX "idx_attachments_review_comment" ON "attachments" ("review_comment_id");"#,
            ),
        ],
        sequence_row: r#"
            INSERT INTO attachments
                (id, uuid, repo_id, uploader_id, filename, blob_key, content_type, size,
                 created_at)
            SELECT {seq}, '_forgekeep_sequence_high_water', 0, 0,
                   '_forgekeep_sequence_high_water', '_forgekeep_sequence_high_water',
                   'application/octet-stream', 0, CURRENT_TIMESTAMP
            WHERE {seq} > COALESCE((SELECT MAX(id) FROM attachments), 0);
            DELETE FROM attachments
            WHERE id = {seq} AND repo_id = 0 AND uuid = '_forgekeep_sequence_high_water';"#,
    },
];

/// Rebuild the three tables with the requested rule, on one pinned connection
/// under an explicit write boundary.
///
/// `foreign_keys` and `legacy_alter_table` are connection-local and cannot be
/// changed after a transaction starts. Acquiring the connection first lets us
/// establish and verify those settings, then `BEGIN IMMEDIATE` excludes every
/// other writer for the whole rebuild. SQLite DDL is transactional, so any
/// error restores all three tables, their indexes and their sequences together.
async fn sqlite_rebuild(manager: &SchemaManager<'_>, shape: Shape) -> Result<(), DbErr> {
    sqlite_rebuild_with_hook(manager, shape, |_| async { Ok(()) }).await
}

/// The rebuild, with a hook the tests use to fail it at a chosen point.
async fn sqlite_rebuild_with_hook<F, Fut>(
    manager: &SchemaManager<'_>,
    shape: Shape,
    after_step: F,
) -> Result<(), DbErr>
where
    F: Fn(SqliteRebuildPoint) -> Fut,
    Fut: Future<Output = Result<(), DbErr>>,
{
    let pool = match manager.get_connection() {
        SchemaManagerConnection::Connection(
            db @ DatabaseConnection::SqlxSqlitePoolConnection(_),
        ) => db.get_sqlite_connection_pool(),
        SchemaManagerConnection::Connection(_) => {
            return Err(DbErr::Migration(
                "m20260805_000002: SQLite rebuild received a non-SQLite connection".to_string(),
            ));
        }
        SchemaManagerConnection::Transaction(_) => {
            return Err(DbErr::Migration(
                "m20260805_000002: SQLite rebuild requires a non-transactional migration \
                 connection so its connection-local PRAGMAs can be set before BEGIN"
                    .to_string(),
            ));
        }
    };
    let mut connection = pool
        .acquire()
        .await
        .map_err(|error| sqlite_error("acquire a dedicated connection", error))?;

    let mut sequences = Vec::with_capacity(SQLITE_TABLES.len());
    for table in &SQLITE_TABLES {
        assert_sqlite_columns(&mut connection, table).await?;
        sequences.push(sqlite_autoincrement_seq(&mut connection, table.name).await?);
    }

    if let Err(error) = prepare_sqlite_rebuild_connection(&mut connection).await {
        return finish_sqlite_rebuild(&mut connection, Err(error), false).await;
    }

    if let Err(error) = sqlite_execute(
        &mut connection,
        "begin the write boundary",
        "BEGIN IMMEDIATE",
    )
    .await
    {
        return finish_sqlite_rebuild(&mut connection, Err(error), false).await;
    }

    let work_result = async {
        after_step(SqliteRebuildPoint::WriteBoundary).await?;
        for (table, sequence) in SQLITE_TABLES.iter().zip(sequences) {
            rebuild_one_table(&mut connection, table, shape, sequence).await?;
            after_step(SqliteRebuildPoint::TableRebuilt(table.name)).await?;
        }
        assert_referential_integrity(&mut connection).await?;
        after_step(SqliteRebuildPoint::SchemaRestored).await?;
        sqlite_execute(&mut connection, "commit the rebuilt tables", "COMMIT").await
    }
    .await;

    finish_sqlite_rebuild(&mut connection, work_result, true).await
}

/// Where a test hook can interrupt the rebuild.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum SqliteRebuildPoint {
    WriteBoundary,
    TableRebuilt(&'static str),
    SchemaRestored,
}

async fn rebuild_one_table(
    connection: &mut SqlitePoolConnection,
    table: &SqliteTable,
    shape: Shape,
    sequence: Option<i64>,
) -> Result<(), DbErr> {
    let name = table.name;
    let staging = format!("{name}_pre_ghost_uploader");
    let columns = table
        .columns
        .iter()
        .map(|column| format!("\"{column}\""))
        .collect::<Vec<_>>()
        .join(", ");
    let body = table.body.replace("{rule}", shape.nullability());
    let foreign_keys = table.foreign_keys.replace("{on_delete}", shape.on_delete());

    let drop_indexes = table
        .indexes
        .iter()
        .map(|(index, _)| format!("DROP INDEX IF EXISTS \"{index}\";"))
        .collect::<String>();
    sqlite_execute(
        connection,
        &format!("drop the {name} indexes"),
        &drop_indexes,
    )
    .await?;

    sqlite_execute(
        connection,
        &format!("copy {name} into the replacement table"),
        &format!(
            r#"
            ALTER TABLE "{name}" RENAME TO "{staging}";

            CREATE TABLE "{name}" ({body},{foreign_keys}
            );

            INSERT INTO "{name}" ({columns}) SELECT {columns} FROM "{staging}";

            DROP TABLE "{staging}";
            "#
        ),
    )
    .await?;

    let restore_indexes = table
        .indexes
        .iter()
        .map(|(_, statement)| *statement)
        .collect::<Vec<_>>()
        .join("\n");
    sqlite_execute(
        connection,
        &format!("restore the {name} indexes"),
        &restore_indexes,
    )
    .await?;

    restore_sequence(connection, table, sequence).await
}

/// Put the table's `AUTOINCREMENT` high-water mark back.
///
/// The replacement table's counter starts from the highest id copied in, which
/// is lower than the old one whenever the most recent row was hard-deleted —
/// and a release-asset id is part of its blob key, so a reused id would name an
/// object a previous asset may still own. A direct `sqlite_sequence` UPDATE
/// inside this transaction is overwritten by SQLite's in-memory sequence state
/// at commit, so the mark is advanced through a real, temporary row instead.
async fn restore_sequence(
    connection: &mut SqlitePoolConnection,
    table: &SqliteTable,
    sequence: Option<i64>,
) -> Result<(), DbErr> {
    let Some(sequence) = sequence else {
        return Ok(());
    };
    sqlite_execute(
        connection,
        &format!("restore the {} AUTOINCREMENT high-water mark", table.name),
        &table.sequence_row.replace("{seq}", &sequence.to_string()),
    )
    .await
}

/// Prove, on this database, that the two pragmas the rebuild depends on still do
/// what it needs — before it touches a row.
///
/// `release_assets` carries `REFERENCES "releases"`, so renaming `releases` out
/// of the way must leave that clause pointing at the *name*: the replacement
/// table then inherits it and dropping the old one cascades nothing. Otherwise
/// SQLite rewrites the clause to follow the rename and the `DROP TABLE` that
/// ends the rebuild silently takes every release asset with it.
///
/// Getting that property needs **both** pragmas, which is not what either one's
/// documentation suggests on its own (established by experiment in
/// `m20260730_000001_repositories_namespace_unique`): `foreign_keys = ON`
/// rewrites the clauses whatever `legacy_alter_table` says, and
/// `legacy_alter_table = OFF` rewrites them whatever `foreign_keys` says.
/// `foreign_keys = OFF` is separately what stops `DROP TABLE`'s implicit
/// `DELETE` from firing `ON DELETE CASCADE`.
///
/// Both are also per-connection and no-ops inside a transaction, and SeaORM
/// happens not to wrap SQLite migrations in one — an implementation detail of a
/// dependency, holding up the difference between a migration and a data loss.
/// So rather than trust the combination, exercise it.
async fn prepare_sqlite_rebuild_connection(
    connection: &mut SqlitePoolConnection,
) -> Result<(), DbErr> {
    sqlite_execute(
        connection,
        "disable foreign keys on the rebuild connection",
        "PRAGMA foreign_keys = OFF",
    )
    .await?;
    sqlite_execute(
        connection,
        "enable legacy ALTER TABLE semantics on the rebuild connection",
        "PRAGMA legacy_alter_table = ON",
    )
    .await?;

    let foreign_keys = sqlite_scalar(
        connection,
        "read PRAGMA foreign_keys",
        "PRAGMA foreign_keys",
    )
    .await?
    .unwrap_or(-1);
    let legacy_alter_table = sqlite_scalar(
        connection,
        "read PRAGMA legacy_alter_table",
        "PRAGMA legacy_alter_table",
    )
    .await?
    .unwrap_or(-1);
    if foreign_keys != 0 || legacy_alter_table != 1 {
        return Err(DbErr::Migration(format!(
            "m20260805_000002: refusing to rebuild the upload tables — the dedicated \
             connection reported foreign_keys={foreign_keys} and \
             legacy_alter_table={legacy_alter_table}, expected 0 and 1"
        )));
    }

    assert_foreign_keys_can_be_suspended(connection).await
}

async fn assert_foreign_keys_can_be_suspended(
    connection: &mut SqlitePoolConnection,
) -> Result<(), DbErr> {
    const PARENT: &str = "_forgekeep_ghost_probe_parent";
    const CHILD: &str = "_forgekeep_ghost_probe_child";
    const RENAMED: &str = "_forgekeep_ghost_probe_parent_renamed";

    let probe_result = async {
        sqlite_execute(
            connection,
            "exercise the foreign-key rename probe",
            &format!(
                r#"
                DROP TABLE IF EXISTS "{CHILD}";
                DROP TABLE IF EXISTS "{PARENT}";
                DROP TABLE IF EXISTS "{RENAMED}";
                CREATE TABLE "{PARENT}" ("id" integer NOT NULL PRIMARY KEY);
                CREATE TABLE "{CHILD}" (
                    "id" integer NOT NULL PRIMARY KEY,
                    "pid" integer NULL REFERENCES "{PARENT}" ("id") ON DELETE CASCADE
                );
                ALTER TABLE "{PARENT}" RENAME TO "{RENAMED}";
                "#
            ),
        )
        .await?;

        sqlite_optional_string(
            connection,
            "read the foreign-key rename probe",
            &format!("SELECT sql FROM sqlite_master WHERE type = 'table' AND name = '{CHILD}'"),
        )
        .await
    }
    .await;

    let cleanup_result = sqlite_execute(
        connection,
        "remove the foreign-key rename probe",
        &format!(r#"DROP TABLE IF EXISTS "{CHILD}"; DROP TABLE IF EXISTS "{RENAMED}";"#),
    )
    .await;

    let child_sql = match (probe_result, cleanup_result) {
        (Ok(child_sql), Ok(())) => child_sql,
        (Err(error), Ok(())) => return Err(error),
        (Ok(_), Err(cleanup_error)) => return Err(cleanup_error),
        (Err(error), Err(cleanup_error)) => {
            return Err(combine_sqlite_errors(error, vec![cleanup_error]));
        }
    };

    let followed_the_rename = child_sql.as_deref().is_none_or(|sql| sql.contains(RENAMED));

    if followed_the_rename {
        return Err(DbErr::Migration(format!(
            "m20260805_000002: refusing to rebuild the upload tables — on this connection \
             `PRAGMA foreign_keys = OFF` did not take effect (the probe table's REFERENCES \
             clause followed the rename: {child_sql:?}). Running the rebuild anyway would drop \
             `releases` while foreign keys are enforced, and every asset of every release would \
             be cascaded away."
        )));
    }

    Ok(())
}

/// Fail loudly if the rebuild left a dangling reference behind.
async fn assert_referential_integrity(connection: &mut SqlitePoolConnection) -> Result<(), DbErr> {
    let violations = sqlite_scalar(
        connection,
        "check the rebuilt tables' foreign keys",
        "SELECT count(*) FROM pragma_foreign_key_check",
    )
    .await?
    .unwrap_or(0);

    if violations > 0 {
        return Err(DbErr::Migration(format!(
            "m20260805_000002: the upload-table rebuild left {violations} dangling foreign key \
             reference(s) behind"
        )));
    }

    Ok(())
}

/// Refuse to rebuild a table whose columns are not the ones this migration
/// knows how to copy.
async fn assert_sqlite_columns(
    connection: &mut SqlitePoolConnection,
    table: &SqliteTable,
) -> Result<(), DbErr> {
    let name = table.name;
    let rows = (&mut **connection)
        .fetch_all(format!("SELECT name FROM pragma_table_info('{name}')").as_str())
        .await
        .map_err(|error| sqlite_error(&format!("read the {name} columns"), error))?;

    let mut live = rows
        .iter()
        .map(|row| {
            row.try_get::<String, _>(0)
                .map_err(|error| sqlite_error(&format!("decode a {name} column"), error))
        })
        .collect::<Result<Vec<_>, _>>()?;
    live.sort();

    let mut expected: Vec<String> = table.columns.iter().map(|c| (*c).to_string()).collect();
    expected.sort();

    if live != expected {
        return Err(DbErr::Migration(format!(
            "m20260805_000002: refusing to rebuild `{name}` — its columns are {live:?}, but this \
             migration copies {expected:?}. A column was added to the table without updating \
             SQLITE_TABLES in this migration; rebuilding now would drop it."
        )));
    }

    Ok(())
}

/// The current `AUTOINCREMENT` high-water mark for a table, if any.
async fn sqlite_autoincrement_seq(
    connection: &mut SqlitePoolConnection,
    table: &str,
) -> Result<Option<i64>, DbErr> {
    sqlite_scalar(
        connection,
        &format!("read the {table} AUTOINCREMENT high-water mark"),
        &format!("SELECT seq FROM sqlite_sequence WHERE name = '{table}'"),
    )
    .await
}

type SqlitePoolConnection = sea_orm::sqlx::pool::PoolConnection<Sqlite>;

async fn sqlite_execute(
    connection: &mut SqlitePoolConnection,
    action: &str,
    sql: &str,
) -> Result<(), DbErr> {
    (&mut **connection)
        .execute(sql)
        .await
        .map(|_| ())
        .map_err(|error| sqlite_error(action, error))
}

async fn sqlite_scalar(
    connection: &mut SqlitePoolConnection,
    action: &str,
    sql: &str,
) -> Result<Option<i64>, DbErr> {
    (&mut **connection)
        .fetch_optional(sql)
        .await
        .map_err(|error| sqlite_error(action, error))?
        .map(|row| {
            row.try_get::<i64, _>(0)
                .map_err(|error| sqlite_error(action, error))
        })
        .transpose()
}

async fn sqlite_optional_string(
    connection: &mut SqlitePoolConnection,
    action: &str,
    sql: &str,
) -> Result<Option<String>, DbErr> {
    (&mut **connection)
        .fetch_optional(sql)
        .await
        .map_err(|error| sqlite_error(action, error))?
        .map(|row| {
            row.try_get::<String, _>(0)
                .map_err(|error| sqlite_error(action, error))
        })
        .transpose()
}

async fn finish_sqlite_rebuild(
    connection: &mut SqlitePoolConnection,
    work_result: Result<(), DbErr>,
    transaction_started: bool,
) -> Result<(), DbErr> {
    let mut cleanup_errors = Vec::new();
    if work_result.is_err() && transaction_started {
        if let Err(error) =
            sqlite_execute(connection, "roll back the rebuilt tables", "ROLLBACK").await
        {
            cleanup_errors.push(error);
        }
    }
    if let Err(error) = sqlite_execute(
        connection,
        "disable legacy ALTER TABLE semantics",
        "PRAGMA legacy_alter_table = OFF",
    )
    .await
    {
        cleanup_errors.push(error);
    }
    if let Err(error) = sqlite_execute(
        connection,
        "restore foreign-key enforcement",
        "PRAGMA foreign_keys = ON",
    )
    .await
    {
        cleanup_errors.push(error);
    }

    match (work_result, cleanup_errors.is_empty()) {
        (Ok(()), true) => Ok(()),
        (Ok(()), false) => {
            connection.close_on_drop();
            Err(combine_sqlite_errors(
                DbErr::Migration(
                    "m20260805_000002: SQLite rebuild committed but connection cleanup failed"
                        .to_string(),
                ),
                cleanup_errors,
            ))
        }
        (Err(error), true) => Err(error),
        (Err(error), false) => {
            connection.close_on_drop();
            Err(combine_sqlite_errors(error, cleanup_errors))
        }
    }
}

fn sqlite_error(action: &str, error: sea_orm::sqlx::Error) -> DbErr {
    DbErr::Migration(format!(
        "m20260805_000002: SQLite rebuild failed to {action}: {error}"
    ))
}

fn combine_sqlite_errors(primary: DbErr, cleanup: Vec<DbErr>) -> DbErr {
    let cleanup = cleanup
        .into_iter()
        .map(|error| error.to_string())
        .collect::<Vec<_>>()
        .join("; ");
    DbErr::Migration(format!("{primary}; cleanup also failed: {cleanup}"))
}

#[cfg(test)]
#[path = "m20260805_000002_uploads_outlive_their_uploader_tests.rs"]
mod tests;

// ── Postgres ────────────────────────────────────────────────────────────────

async fn postgres_apply(manager: &SchemaManager<'_>, shape: Shape) -> Result<(), DbErr> {
    let db = manager.get_connection();

    for (table, column) in GHOSTED_COLUMNS {
        // Named rather than server-generated, so the reversal can find it by
        // the same route this call created it.
        let constraint = format!("fk_{table}_{column}_users");
        if let Some(existing) = postgres_foreign_key(manager, table, column).await? {
            db.execute_unprepared(&format!(
                r#"ALTER TABLE "{table}" DROP CONSTRAINT "{existing}""#
            ))
            .await?;
        }

        let nullability = match shape {
            Shape::Ghost => "DROP NOT NULL",
            Shape::Owned => "SET NOT NULL",
        };
        db.execute_unprepared(&format!(
            r#"ALTER TABLE "{table}" ALTER COLUMN "{column}" {nullability}"#
        ))
        .await?;

        db.execute_unprepared(&format!(
            r#"ALTER TABLE "{table}" ADD CONSTRAINT "{constraint}"
               FOREIGN KEY ("{column}") REFERENCES "users" ("id") ON DELETE {}"#,
            shape.on_delete()
        ))
        .await?;
    }

    Ok(())
}

/// Name of the foreign key on `table.column` that points at `users`.
///
/// Looked up rather than assumed: the constraint was declared inline by SeaORM
/// and its name is whatever the server generated.
async fn postgres_foreign_key(
    manager: &SchemaManager<'_>,
    table: &str,
    column: &str,
) -> Result<Option<String>, DbErr> {
    let row = manager
        .get_connection()
        .query_one(Statement::from_sql_and_values(
            DatabaseBackend::Postgres,
            r#"
            SELECT con.conname AS conname
            FROM pg_constraint con
            JOIN pg_class rel ON rel.oid = con.conrelid
            JOIN pg_namespace ns ON ns.oid = rel.relnamespace
            JOIN pg_class ref ON ref.oid = con.confrelid
            WHERE rel.relname = $1
              AND ns.nspname = current_schema()
              AND con.contype = 'f'
              AND ref.relname = 'users'
              AND (
                SELECT string_agg(att.attname::text, ',' ORDER BY att.attname)
                FROM unnest(con.conkey) AS k(attnum)
                JOIN pg_attribute att
                  ON att.attrelid = con.conrelid AND att.attnum = k.attnum
              ) = $2
            LIMIT 1
            "#,
            [table.into(), column.into()],
        ))
        .await?;

    match row {
        Some(row) => Ok(Some(row.try_get::<String>("", "conname")?)),
        None => Ok(None),
    }
}

// ── MySQL ───────────────────────────────────────────────────────────────────

async fn mysql_apply(manager: &SchemaManager<'_>, shape: Shape) -> Result<(), DbErr> {
    let db = manager.get_connection();

    for (table, column) in GHOSTED_COLUMNS {
        let constraint = format!("fk_{table}_{column}_users");
        if let Some(existing) = mysql_foreign_key(manager, table, column).await? {
            db.execute_unprepared(&format!(
                "ALTER TABLE `{table}` DROP FOREIGN KEY `{existing}`"
            ))
            .await?;
        }

        // MySQL has no "alter only the nullability": the column has to be
        // restated, and `bigint` is what every one of these columns is.
        db.execute_unprepared(&format!(
            "ALTER TABLE `{table}` MODIFY `{column}` BIGINT {}",
            shape.nullability()
        ))
        .await?;

        // Dropping the foreign key leaves its index behind, which is what the
        // re-added constraint needs to live on — so no index is created here.
        db.execute_unprepared(&format!(
            "ALTER TABLE `{table}` ADD CONSTRAINT `{constraint}`
             FOREIGN KEY (`{column}`) REFERENCES `users` (`id`) ON DELETE {}",
            shape.on_delete()
        ))
        .await?;
    }

    Ok(())
}

/// Name of the foreign key on `table.column` that points at `users`.
async fn mysql_foreign_key(
    manager: &SchemaManager<'_>,
    table: &str,
    column: &str,
) -> Result<Option<String>, DbErr> {
    let row = manager
        .get_connection()
        .query_one(Statement::from_sql_and_values(
            DatabaseBackend::MySql,
            "SELECT k.CONSTRAINT_NAME AS name
             FROM information_schema.KEY_COLUMN_USAGE k
             WHERE k.TABLE_SCHEMA = DATABASE()
               AND k.TABLE_NAME = ?
               AND k.COLUMN_NAME = ?
               AND k.REFERENCED_TABLE_NAME = 'users'
             LIMIT 1",
            [table.into(), column.into()],
        ))
        .await?;

    match row {
        Some(row) => Ok(Some(row.try_get::<String>("", "name")?)),
        None => Ok(None),
    }
}
