//! `repositories` held one name per **account**, not one per namespace.
//!
//! The table was born with an inline `UNIQUE ("owner_id", "name")`
//! (`m20260424_000002_create_repositories`), and an organization's repository
//! hangs off its owner's user row (`owner_id = org.owner_id`, see
//! `rg_core::repo::service::resolve_owner`). So the *table* could physically
//! hold only one repository called `db` per account — a personal `alice/db` and
//! an `acme/db` owned by alice were a constraint violation, however carefully
//! the queries above it distinguished the two namespaces (card_92019cc97dcd
//! fixed the query side; this is the schema side, card_615e00843297).
//!
//! The replacement is a stored generated column, `namespace_key`, plus
//! `UNIQUE (namespace_key, name)`:
//!
//! * `'o<org_id>'` for an organization's repository, `'u<owner_id>'` for a
//!   personal one — so the key *is* the namespace, and moving a repository
//!   between them moves which slot it occupies.
//! * `NULL` for a soft-deleted row. Every lookup already filters
//!   `deleted_at IS NULL`, so a deleted repository is invisible to the code but
//!   used to keep holding its name hostage in the index. All three backends
//!   treat NULLs in a unique index as distinct, which is exactly the "occupies
//!   no slot" semantics wanted here.
//!
//!   (Reusing a deleted repository's name end-to-end takes one more fix that is
//!   not the schema's: `delete_repo` soft-deletes the row and leaves
//!   `<repo_root>/<owner>/<name>.git` on disk, so the recreate now clears the
//!   database and dies in `gix init --bare` instead — card_9b6fa1a621a0.)
//!
//! A generated column rather than the two obvious alternatives, because it is
//! the only one that ports to all three backends: partial unique indexes
//! (`WHERE org_id IS NULL`) do not exist in MySQL at all, and functional
//! indexes do not exist in MariaDB. It is `STORED` on SQLite and Postgres and
//! `VIRTUAL` on MySQL — see `mysql_up` for why, which is the only place the
//! three schemas are not the same shape.
//!
//! Uniqueness stays enforced by the database, not by the service layer.
//!
//! ## Per-backend notes
//!
//! **SQLite** — the old constraint is *inline in `CREATE TABLE`*, so there is no
//! index to drop; the table has to be rebuilt. Seventeen tables reference
//! `repositories` with `ON DELETE CASCADE`, which makes the rebuild the
//! dangerous part rather than the constraint: it is done under
//! `PRAGMA foreign_keys = OFF` **and** `PRAGMA legacy_alter_table = ON`
//! together, because either one alone still lets SQLite rewrite those
//! `REFERENCES` clauses to follow the rename — after which the closing
//! `DROP TABLE` cascades every issue, pull request and star away. The whole
//! rebuild is one `execute_unprepared` batch so the pragmas and the statements
//! they govern cannot land on different pool connections, and
//! `assert_foreign_keys_can_be_suspended` proves the combination still holds on
//! this database *before* the first destructive statement runs.
//!
//! **Postgres / MySQL** — the constraint is a real index, but an unnamed one:
//! its name was generated by the server (`repositories_owner_id_name_key` /
//! `owner_id`). Both are looked up in the catalogue by their *column set* rather
//! than assumed, so a database created by a different SeaORM or server version
//! is handled too.
//!
//! A plain `(owner_id, name)` index is created on every backend before the
//! unique one is dropped. It preserves the lookup the unique index was
//! incidentally serving (`find_personal_by_owner_and_name`,
//! `list_personal_by_owner`), and on MySQL it is also what lets the old index be
//! dropped at all — the `owner_id` foreign key needs an index to live on.

use sea_orm::{ConnectionTrait, DatabaseBackend, Statement};
use sea_orm_migration::prelude::*;

pub struct Migration;

impl MigrationName for Migration {
    fn name(&self) -> &str {
        "m20260730_000001_repositories_namespace_unique"
    }
}

/// The unique index that replaces the account-wide `UNIQUE (owner_id, name)`.
const NAMESPACE_INDEX: &str = "uq_repositories_namespace_name";
/// Non-unique stand-in for the lookups the old unique index also served.
const OWNER_NAME_INDEX: &str = "idx_repositories_owner_id_name";

/// Columns of `repositories` as of this migration, in the order the SQLite
/// rebuild copies them. Checked against the live table before anything is
/// dropped — a rebuild that silently loses a column added by a migration this
/// one has not heard of would be far worse than a refusal to run.
const SQLITE_COLUMNS: [&str; 14] = [
    "id",
    "owner_id",
    "name",
    "description",
    "is_private",
    "default_branch",
    "fork_id",
    "stars_count",
    "forks_count",
    "created_at",
    "updated_at",
    "org_id",
    "deleted_at",
    "origin_repo_id",
];

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        match manager.get_database_backend() {
            DatabaseBackend::Sqlite => sqlite_rebuild(manager, Shape::NamespaceKey).await,
            DatabaseBackend::Postgres => postgres_up(manager).await,
            DatabaseBackend::MySql => mysql_up(manager).await,
        }
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        match manager.get_database_backend() {
            DatabaseBackend::Sqlite => sqlite_rebuild(manager, Shape::OwnerAccount).await,
            DatabaseBackend::Postgres => postgres_down(manager).await,
            DatabaseBackend::MySql => mysql_down(manager).await,
        }
    }
}

/// Which uniqueness the rebuilt SQLite table is to carry.
///
/// `down` is a real reversal rather than a half-revert: it puts the account-wide
/// constraint back. If repositories that only the new rule allows have been
/// created since, restoring it fails loudly — which is the honest answer, the
/// rows cannot go back.
#[derive(Clone, Copy)]
enum Shape {
    NamespaceKey,
    OwnerAccount,
}

// ── SQLite ──────────────────────────────────────────────────────────────────

/// The generated column, spelled for SQLite (`||` concatenates).
const SQLITE_NAMESPACE_KEY: &str = r#""namespace_key" text GENERATED ALWAYS AS (
        CASE WHEN "deleted_at" IS NOT NULL THEN NULL
             WHEN "org_id" IS NULL THEN 'u' || "owner_id"
             ELSE 'o' || "org_id" END) STORED"#;

/// The three FTS triggers on `repositories`. The rebuild drops and recreates
/// them, so this copy must retain the live-row semantics installed by
/// `m20260804_000006_repo_fts_soft_delete` even when the namespace migration is
/// rolled back later.
const SQLITE_FTS_TRIGGERS: &str = r#"
    CREATE TRIGGER IF NOT EXISTS repos_fts_insert AFTER INSERT ON repositories
    WHEN new.deleted_at IS NULL BEGIN
        INSERT INTO repos_fts(rowid, name, description)
        VALUES (new.id, new.name, COALESCE(new.description, ''));
    END;

    CREATE TRIGGER IF NOT EXISTS repos_fts_delete AFTER DELETE ON repositories BEGIN
        DELETE FROM repos_fts WHERE rowid = old.id;
    END;

    CREATE TRIGGER IF NOT EXISTS repos_fts_update AFTER UPDATE ON repositories BEGIN
        DELETE FROM repos_fts WHERE rowid = old.id;
        INSERT INTO repos_fts(rowid, name, description)
        SELECT new.id, new.name, COALESCE(new.description, '')
        WHERE new.deleted_at IS NULL;
    END;
"#;

/// Rebuild `repositories` with the requested uniqueness.
///
/// SQLite cannot drop a constraint declared inside `CREATE TABLE`, so this is
/// the documented table-rebuild (see the module header for why foreign key
/// enforcement has to be suspended across it).
async fn sqlite_rebuild(manager: &SchemaManager<'_>, shape: Shape) -> Result<(), DbErr> {
    let db = manager.get_connection();

    assert_sqlite_columns(manager).await?;
    assert_foreign_keys_can_be_suspended(manager).await?;
    let sequence = sqlite_autoincrement_seq(manager).await?;

    let (extra_column, table_constraint, extra_index) = match shape {
        Shape::NamespaceKey => (
            format!(",\n        {SQLITE_NAMESPACE_KEY}"),
            String::new(),
            format!(
                r#"CREATE UNIQUE INDEX "{NAMESPACE_INDEX}" ON "repositories" ("namespace_key", "name");"#
            ),
        ),
        Shape::OwnerAccount => (
            String::new(),
            ",\n        UNIQUE (\"owner_id\", \"name\")".to_string(),
            String::new(),
        ),
    };

    let columns = SQLITE_COLUMNS
        .iter()
        .map(|column| format!("\"{column}\""))
        .collect::<Vec<_>>()
        .join(", ");

    let sql = format!(
        r#"
        PRAGMA foreign_keys = OFF;
        PRAGMA legacy_alter_table = ON;

        DROP TRIGGER IF EXISTS repos_fts_insert;
        DROP TRIGGER IF EXISTS repos_fts_delete;
        DROP TRIGGER IF EXISTS repos_fts_update;
        DROP INDEX IF EXISTS "idx_repositories_org_id";
        DROP INDEX IF EXISTS "idx_repositories_origin_repo_id";
        DROP INDEX IF EXISTS "{OWNER_NAME_INDEX}";
        DROP INDEX IF EXISTS "{NAMESPACE_INDEX}";

        ALTER TABLE "repositories" RENAME TO "repositories_pre_namespace_key";

        CREATE TABLE "repositories" (
            "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
            "owner_id" bigint NOT NULL,
            "name" varchar NOT NULL,
            "description" text NULL,
            "is_private" boolean NOT NULL DEFAULT FALSE,
            "default_branch" varchar NOT NULL DEFAULT 'main',
            "fork_id" bigint NULL,
            "stars_count" bigint NOT NULL DEFAULT 0,
            "forks_count" bigint NOT NULL DEFAULT 0,
            "created_at" timestamp_with_timezone_text NOT NULL,
            "updated_at" timestamp_with_timezone_text NOT NULL,
            "org_id" bigint NULL,
            "deleted_at" timestamp_with_timezone_text NULL,
            "origin_repo_id" bigint NULL{extra_column}{table_constraint},
            FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON DELETE CASCADE
        );

        INSERT INTO "repositories" ({columns})
            SELECT {columns} FROM "repositories_pre_namespace_key";

        DROP TABLE "repositories_pre_namespace_key";

        {extra_index}
        CREATE INDEX "{OWNER_NAME_INDEX}" ON "repositories" ("owner_id", "name");
        CREATE INDEX "idx_repositories_org_id" ON "repositories" ("org_id");
        CREATE INDEX "idx_repositories_origin_repo_id" ON "repositories" ("origin_repo_id");

        {SQLITE_FTS_TRIGGERS}

        PRAGMA legacy_alter_table = OFF;
        PRAGMA foreign_keys = ON;
        "#
    );

    db.execute_unprepared(&sql).await?;
    assert_referential_integrity(manager).await?;

    // The new table's AUTOINCREMENT counter starts from the highest id copied
    // in, which is lower than the old one whenever the most recent repository
    // was hard-deleted. Restore it, or the next repository created reuses an id
    // that already appeared in URLs, audit rows and on disk.
    if let Some(seq) = sequence {
        db.execute(Statement::from_sql_and_values(
            DatabaseBackend::Sqlite,
            "INSERT OR REPLACE INTO sqlite_sequence(name, seq) VALUES ('repositories', ?)",
            [seq.into()],
        ))
        .await?;
    }

    Ok(())
}

/// Prove, on this database, that the two pragmas the rebuild depends on still do
/// what it needs — before it touches a row.
///
/// The procedure rests on one property: renaming `repositories` out of the way
/// must leave the 17 incoming `REFERENCES "repositories"` clauses pointing at
/// the *name*, so the new table inherits them and dropping the old one cascades
/// nothing. Otherwise SQLite rewrites those clauses to follow the rename, and
/// the `DROP TABLE` that ends the rebuild silently takes every issue, pull
/// request and star with it.
///
/// Getting that property needs **both** pragmas, which is not what either one's
/// documentation suggests on its own and was established by experiment:
/// `foreign_keys = ON` rewrites the clauses whatever `legacy_alter_table` says,
/// and `legacy_alter_table = OFF` rewrites them whatever `foreign_keys` says.
/// `foreign_keys = OFF` is separately what stops `DROP TABLE`'s implicit
/// `DELETE` from firing `ON DELETE CASCADE`.
///
/// Both are also per-connection and no-ops inside a transaction, and SeaORM
/// happens not to wrap SQLite migrations in one — an implementation detail of a
/// dependency, holding up the difference between a migration and a data loss.
/// So rather than trust the combination, exercise it: rename a throwaway parent
/// and read back whether its child's `REFERENCES` clause followed.
async fn assert_foreign_keys_can_be_suspended(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    const PARENT: &str = "_forgekeep_fk_probe_parent";
    const CHILD: &str = "_forgekeep_fk_probe_child";
    const RENAMED: &str = "_forgekeep_fk_probe_parent_renamed";

    let db = manager.get_connection();

    db.execute_unprepared(&format!(
        r#"
        DROP TABLE IF EXISTS "{CHILD}";
        DROP TABLE IF EXISTS "{PARENT}";
        DROP TABLE IF EXISTS "{RENAMED}";

        PRAGMA foreign_keys = OFF;
        PRAGMA legacy_alter_table = ON;
        CREATE TABLE "{PARENT}" ("id" integer NOT NULL PRIMARY KEY);
        CREATE TABLE "{CHILD}" (
            "id" integer NOT NULL PRIMARY KEY,
            "pid" integer NULL REFERENCES "{PARENT}" ("id") ON DELETE CASCADE
        );
        ALTER TABLE "{PARENT}" RENAME TO "{RENAMED}";
        PRAGMA legacy_alter_table = OFF;
        PRAGMA foreign_keys = ON;
        "#
    ))
    .await?;

    let child_sql = manager
        .get_connection()
        .query_one(Statement::from_sql_and_values(
            DatabaseBackend::Sqlite,
            "SELECT sql FROM sqlite_master WHERE type = 'table' AND name = ?",
            [CHILD.into()],
        ))
        .await?
        .map(|row| row.try_get::<String>("", "sql"))
        .transpose()?;

    db.execute_unprepared(&format!(
        r#"DROP TABLE IF EXISTS "{CHILD}"; DROP TABLE IF EXISTS "{RENAMED}";"#
    ))
    .await?;

    let followed_the_rename = child_sql.as_deref().is_none_or(|sql| sql.contains(RENAMED));

    if followed_the_rename {
        return Err(DbErr::Migration(format!(
            "m20260730_000001: refusing to rebuild `repositories` — on this connection \
             `PRAGMA foreign_keys = OFF` did not take effect (the probe table's REFERENCES \
             clause followed the rename: {child_sql:?}). Running the rebuild anyway would \
             drop the table while foreign keys are enforced, and every row referencing a \
             repository would be cascaded away."
        )));
    }

    Ok(())
}

/// Fail loudly if the rebuild left a dangling reference behind.
async fn assert_referential_integrity(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    let row = manager
        .get_connection()
        .query_one(Statement::from_string(
            DatabaseBackend::Sqlite,
            "SELECT count(*) AS violations FROM pragma_foreign_key_check",
        ))
        .await?;

    let violations = match row {
        Some(row) => row.try_get::<i64>("", "violations")?,
        None => 0,
    };

    if violations > 0 {
        return Err(DbErr::Migration(format!(
            "m20260730_000001: the `repositories` rebuild left {violations} dangling foreign \
             key reference(s) behind"
        )));
    }

    Ok(())
}

/// Refuse to rebuild a table whose columns are not the ones this migration
/// knows how to copy.
async fn assert_sqlite_columns(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    let rows = manager
        .get_connection()
        .query_all(Statement::from_string(
            DatabaseBackend::Sqlite,
            "SELECT name FROM pragma_table_info('repositories')",
        ))
        .await?;

    let mut live: Vec<String> = Vec::with_capacity(rows.len());
    for row in &rows {
        live.push(row.try_get::<String>("", "name")?);
    }
    live.sort();

    let mut expected: Vec<String> = SQLITE_COLUMNS.iter().map(|c| (*c).to_string()).collect();
    // The rebuild is also the `down` path, where the column is already there.
    if live.iter().any(|column| column == "namespace_key") {
        expected.push("namespace_key".to_string());
    }
    expected.sort();

    if live != expected {
        return Err(DbErr::Migration(format!(
            "m20260730_000001: refusing to rebuild `repositories` — its columns are {live:?}, \
             but this migration copies {expected:?}. A column was added to the table without \
             updating SQLITE_COLUMNS in this migration; rebuilding now would drop it."
        )));
    }

    Ok(())
}

/// The current `AUTOINCREMENT` high-water mark for `repositories`, if any.
async fn sqlite_autoincrement_seq(manager: &SchemaManager<'_>) -> Result<Option<i64>, DbErr> {
    let row = manager
        .get_connection()
        .query_one(Statement::from_string(
            DatabaseBackend::Sqlite,
            "SELECT seq FROM sqlite_sequence WHERE name = 'repositories'",
        ))
        .await?;

    match row {
        Some(row) => Ok(Some(row.try_get::<i64>("", "seq")?)),
        None => Ok(None),
    }
}

// ── Postgres ────────────────────────────────────────────────────────────────

async fn postgres_up(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    let db = manager.get_connection();

    db.execute_unprepared(&format!(
        r#"CREATE INDEX IF NOT EXISTS "{OWNER_NAME_INDEX}" ON repositories (owner_id, name)"#
    ))
    .await?;

    if let Some(constraint) = postgres_unique_constraint(manager, "name,owner_id").await? {
        db.execute_unprepared(&format!(
            r#"ALTER TABLE repositories DROP CONSTRAINT "{constraint}""#
        ))
        .await?;
    }

    db.execute_unprepared(
        r#"ALTER TABLE repositories ADD COLUMN IF NOT EXISTS namespace_key text
           GENERATED ALWAYS AS (
               CASE WHEN deleted_at IS NOT NULL THEN NULL
                    WHEN org_id IS NULL THEN 'u' || owner_id::text
                    ELSE 'o' || org_id::text END) STORED"#,
    )
    .await?;

    db.execute_unprepared(&format!(
        r#"CREATE UNIQUE INDEX IF NOT EXISTS "{NAMESPACE_INDEX}"
           ON repositories (namespace_key, name)"#
    ))
    .await?;

    Ok(())
}

async fn postgres_down(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    let db = manager.get_connection();

    db.execute_unprepared(&format!(r#"DROP INDEX IF EXISTS "{NAMESPACE_INDEX}""#))
        .await?;
    db.execute_unprepared("ALTER TABLE repositories DROP COLUMN IF EXISTS namespace_key")
        .await?;
    if postgres_unique_constraint(manager, "name,owner_id")
        .await?
        .is_none()
    {
        db.execute_unprepared("ALTER TABLE repositories ADD UNIQUE (owner_id, name)")
            .await?;
    }
    db.execute_unprepared(&format!(r#"DROP INDEX IF EXISTS "{OWNER_NAME_INDEX}""#))
        .await?;

    Ok(())
}

/// Name of the unique constraint on `repositories` covering exactly `columns`
/// (comma-joined, sorted by column name).
///
/// Looked up rather than assumed: the constraint was declared inline and
/// unnamed, so its name is whatever the server generated.
async fn postgres_unique_constraint(
    manager: &SchemaManager<'_>,
    columns: &str,
) -> Result<Option<String>, DbErr> {
    let row = manager
        .get_connection()
        .query_one(Statement::from_sql_and_values(
            DatabaseBackend::Postgres,
            r#"
            SELECT con.conname AS conname
            FROM pg_constraint con
            JOIN pg_class rel ON rel.oid = con.conrelid
            JOIN pg_namespace ns ON ns.oid = rel.relnamespace
            WHERE rel.relname = 'repositories'
              AND ns.nspname = current_schema()
              AND con.contype = 'u'
              AND (
                SELECT string_agg(att.attname::text, ',' ORDER BY att.attname)
                FROM unnest(con.conkey) AS k(attnum)
                JOIN pg_attribute att
                  ON att.attrelid = con.conrelid AND att.attnum = k.attnum
              ) = $1
            LIMIT 1
            "#,
            [columns.into()],
        ))
        .await?;

    match row {
        Some(row) => Ok(Some(row.try_get::<String>("", "conname")?)),
        None => Ok(None),
    }
}

// ── MySQL ───────────────────────────────────────────────────────────────────

async fn mysql_up(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    let db = manager.get_connection();

    // Before the unique index goes: the `owner_id` foreign key needs an index
    // to live on, and MySQL refuses to drop the last one that covers it.
    if mysql_index(manager, "name,owner_id", OWNER_NAME_INDEX)
        .await?
        .is_none()
    {
        db.execute_unprepared(&format!(
            "CREATE INDEX `{OWNER_NAME_INDEX}` ON repositories (owner_id, name)"
        ))
        .await?;
    }

    if let Some(index) = mysql_unique_index(manager, "name,owner_id").await? {
        db.execute_unprepared(&format!("ALTER TABLE repositories DROP INDEX `{index}`"))
            .await?;
    }

    if mysql_column_exists(manager, "namespace_key").await? {
        return Ok(());
    }

    // VIRTUAL, not STORED — the one place the three backends genuinely differ.
    // MySQL refuses a *stored* generated column whose base column carries a
    // foreign key with `ON DELETE CASCADE`, and `owner_id` is exactly that
    // (`repositories_ibfk_1 → users(id) ON DELETE CASCADE`); the attempt comes
    // back as a bare `1215 Cannot add foreign key constraint`. The restriction
    // does not apply to virtual columns, and a secondary index over one is
    // materialized, so uniqueness is enforced by the index just the same.
    db.execute_unprepared(
        "ALTER TABLE repositories ADD COLUMN namespace_key VARCHAR(32)
         GENERATED ALWAYS AS (
             CASE WHEN deleted_at IS NOT NULL THEN NULL
                  WHEN org_id IS NULL THEN CONCAT('u', owner_id)
                  ELSE CONCAT('o', org_id) END) VIRTUAL",
    )
    .await?;

    db.execute_unprepared(&format!(
        "CREATE UNIQUE INDEX `{NAMESPACE_INDEX}` ON repositories (namespace_key, name)"
    ))
    .await?;

    Ok(())
}

async fn mysql_down(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    let db = manager.get_connection();

    if mysql_index(manager, "name,namespace_key", NAMESPACE_INDEX)
        .await?
        .is_some()
    {
        db.execute_unprepared(&format!(
            "ALTER TABLE repositories DROP INDEX `{NAMESPACE_INDEX}`"
        ))
        .await?;
    }
    if mysql_column_exists(manager, "namespace_key").await? {
        db.execute_unprepared("ALTER TABLE repositories DROP COLUMN namespace_key")
            .await?;
    }
    if mysql_unique_index(manager, "name,owner_id")
        .await?
        .is_none()
    {
        db.execute_unprepared("ALTER TABLE repositories ADD UNIQUE (owner_id, name)")
            .await?;
    }
    if let Some(index) = mysql_index(manager, "name,owner_id", OWNER_NAME_INDEX).await? {
        db.execute_unprepared(&format!("ALTER TABLE repositories DROP INDEX `{index}`"))
            .await?;
    }

    Ok(())
}

/// Name of the *unique* index on `repositories` whose columns are exactly
/// `columns` (comma-joined, sorted by column name).
async fn mysql_unique_index(
    manager: &SchemaManager<'_>,
    columns: &str,
) -> Result<Option<String>, DbErr> {
    mysql_index_matching(manager, columns, "AND s.NON_UNIQUE = 0", None).await
}

/// Same lookup, restricted to one index name — used to make the `CREATE INDEX`
/// calls idempotent (MySQL has no `CREATE INDEX IF NOT EXISTS`).
async fn mysql_index(
    manager: &SchemaManager<'_>,
    columns: &str,
    name: &str,
) -> Result<Option<String>, DbErr> {
    mysql_index_matching(manager, columns, "", Some(name)).await
}

async fn mysql_index_matching(
    manager: &SchemaManager<'_>,
    columns: &str,
    uniqueness: &str,
    name: Option<&str>,
) -> Result<Option<String>, DbErr> {
    let by_name = match name {
        Some(_) => "AND s.INDEX_NAME = ?",
        None => "",
    };
    let sql = format!(
        "SELECT s.INDEX_NAME AS idx
         FROM information_schema.STATISTICS s
         WHERE s.TABLE_SCHEMA = DATABASE()
           AND s.TABLE_NAME = 'repositories'
           {uniqueness}
           {by_name}
         GROUP BY s.INDEX_NAME
         HAVING GROUP_CONCAT(s.COLUMN_NAME ORDER BY s.COLUMN_NAME) = ?
         LIMIT 1"
    );

    let values: Vec<sea_orm::Value> = match name {
        Some(name) => vec![name.into(), columns.into()],
        None => vec![columns.into()],
    };

    let row = manager
        .get_connection()
        .query_one(Statement::from_sql_and_values(
            DatabaseBackend::MySql,
            &sql,
            values,
        ))
        .await?;

    match row {
        Some(row) => Ok(Some(row.try_get::<String>("", "idx")?)),
        None => Ok(None),
    }
}

async fn mysql_column_exists(manager: &SchemaManager<'_>, column: &str) -> Result<bool, DbErr> {
    let row = manager
        .get_connection()
        .query_one(Statement::from_sql_and_values(
            DatabaseBackend::MySql,
            "SELECT COLUMN_NAME AS col
             FROM information_schema.COLUMNS
             WHERE TABLE_SCHEMA = DATABASE()
               AND TABLE_NAME = 'repositories'
               AND COLUMN_NAME = ?",
            [column.into()],
        ))
        .await?;

    Ok(row.is_some())
}
